index_setsm.py
The index_setsm.py script needs to be callable from scripts external to this repo. This is doable in its current state (using Python's importlib module), but will not return a Python-readable status upon success or failure. While the ideal solution would be to refactor most of it into its own function, the simplest and least disruptive fix is to have the script return a True or False at the end, depending on if it succeeded or not. This change is transparent if the script is run from the command line. 
Other changes were made to ensure compatibility for both Python 2 and 3.
=> index_setsm.py status return, py 2to3 updates

index_setsm.py
Allow main() function to return status of OGR layer writing. This is necessary when calling index_setsm.py externally from another script to handle exceptions.
=> Return write response to main() function

index_setsm.py
The original intent with PR #2 and PR #3 was to make this index_setsm.py importable to other repos, so indexing could happen after a number of conditions were met. However, the library requirements for this repo (Python GDAL, with psql and SSL support) vary significantly from our other PGC-specific GDAL builds, making it not possible to import. 
This PR simply changes any script exit condition to respond with sys.exit(0) upon success, and sys.exit(-1) upon failure (instead of 'return True' or 'return False'). This makes response handling possible in shell (e.g., bash) as well as being imported in Python (will throw SystemExit exception).
=> always exit with system-readable status code

index_setsm.py, lib/dem.py, lib/utils.py, package_setsm.py, tests/func_test_index.py
Indexer changes: 
1) Optional GCP fields for strips and tiles
2) Index 2m Dsp as 2m DEM
3) Index 2m Dsp as 50cm DEM substitute with info50cm txt files with aux info
4) Add file size for ortho2 for scenes and strips
5) Added is_xtrack, stripdemid, edgemask, matermask, cloudmask fields in strips
6) Added is_xtrack, is_dsp fields in scenes
7) Option to search for masked DEM strips
8) Custom status option
9) Doubled length of location field is all types, added field length check for setting fields
=> Incorporate downsampled products; make stripDEM changes

apply_setsm_registration.py, calc_density.py, calc_density_tiles.py, copy_dems.py, divide_setsm_tiles.py, generate_browse_setsm.py, index_setsm.py, lib/dem.py, lib/utils.py, package_setsm.py, package_setsm_tiles.py, rename_setsm_add_version.py, resample_setsm_tiles.py, shelve_setsm_by_date.py, shelve_setsm_by_geocell.py, shelve_setsm_by_shp.py, tests/func_test_index.py
I added a --check option for the indexer that verifies the presence of the required records in the target layer after writing them by building a key made up of three components:
- DEM ID (scenedemid and stripdemid, dem_id and stripdemid, or dem_id and tile depending on the mode)
- LOCATION
- INDEX_DATE
It is technically possible to have a false positive, but not likely given the way we use this tool. This option was built to handle instances where records are not written to postgres, but no error is thrown.  Perhaps it can help simplify Danny's ingest checks as well.
=> Option to verify indexer wrote required records to target layer

lib/dem.py, lib/utils.py
Last week I pushed the scenes2strips code as far as I could in post-processing 50cm DEMs on Nunatak. I actually got a working Conda environment using Jim's GDAL build with the LERC codec & FileGDB, that could also play with OpenCV!!!
In the process, I noticed that GDAL was not automatically converting the scaled int 50cm DEM rasters when read into python using the normal process:
```
ds = gdal.Open("file")
band = ds.GetRasterBand(1)
dem_data = band.ReadAsArray()
```
The `dem_data` array you get from is in Int32 data type with the scaling still applied (scale factor = 100x original elev values).
After some back and forth with Jim, I wrote up the function `gdalReadAsArraySetsmSceneBand()` to be added to `utils.py` in this PR. **It's very important** that we use this function whenever doing …
=> Properly read scaled int LERC_ZSTD compressed dems

apply_setsm_registration.py
gdal_calc.py does not like gdalwarp or gdal_translate, it would not copy the nodata from the source file, so we need to manually set the nodata
=> add nodata (-9999) back for gdal_calc.py

config.ini.example, index_setsm.py, tests/func_test_index.py
1) Index_setsm now supports writing 1 or 2 records for a downsampled product (DSP), in the current res, one in the original res, or both.
2) The --dsp-record mode-orig-status option was introduced to handle the custom status of DSP original res records when both resolutions are being handled.
3) BP and PGC path refixes were merged into a --custom-paths option and a CSS option as added
4) BP paths were updated to use the new tape bucket scheme.
5) A --np option was added to suppress progress bar use.
=> Modifications to index_setsm.py to support DSP and custom paths

index_setsm.py, lib/dem.py
When using the index_setsm.py `--write-json` option to verify strips (`--mode='strips'`), we want the JSON files written next to the strip folders. Problem is that the JSON filenames were being created based on the DEM's `stripdemid` attribute, which doesn't include the "_lsf" part of the strip folder names. So I made an adjustment to use a new DEM attribute called `stripdirname`, which includes the "_lsf" part, if applicable.
Added a couple other convenience tweaks to index_setsm.py as well.
=> Correct strip JSON filenames, couple other tweaks

calc_density.py, index_setsm.py, lib/dem.py, lib/utils.py, package_setsm.py, package_setsm_tiles.py, qsub_package.sh, tests/func_test_index.py
- Introduced the masked density concept and rolled it out in  package_setsm and index_setsm.
- Added better handling of density, masked density, min and max elevation values in dem.py
- Updated index_setsm to handle unset EPSG codes in pre-built jsons.
- Added a flag making it optional to skip original resolution DSP records when no original file size info was found.
- Added check for Strip DEM ID in strip dem metadata to report version and derive custom file location correctly.
- Updated code around removing strips with low data density in the package_setsm code and raised the threshold to 0.2.
=> Update Packaging and Strip Metadata

lib/dem.py, lib/utils.py, package_setsm.py, shelve_setsm_strips_simple.py
This PR adds COG creation functionality to package_setsm.py.  COG compression is LZW with predictor=yes (2 to 3) for all files except the bitmasks and matchtags, which use predictor=no (1).  The packager also includes the 10m_shade_masked file in addition to the unmasked shade file. The shelve_setm_strip_simple.py script can now also take a text file of input dems instead of only a dir or file.
=> COG package strips

index_setsm.py, tests/func_test_index.py
When using index_setsm.py to make 50cm records from a 2m_dsp DEM, bypass the 50cminfo.txt files and set the files size attributes to null.
=> Bypass 50cminfo

lib/dem.py
I noticed that usage of an offshoot of one of these regex patterns in the shelve-setsm-dems repo was catching more source files than it was supposed to, because the period in the file extension part of the regex was not escaped.
@clairecporter I don't have any particular error cases that I've hit with index_setsm.py concerning this issue so far, but could run your standard tests for these regex fixes at some point?
=> Escape literal periods used in regex patterns

lib/dem.py
These are the new `SetsmTile` attributes:
- `pairname_ids`: list of stereo pairnames of strips that make up the mosaic tile data, to be mapped to STAC `pgc:pairname_ids[]` property
- `acqdate_min`: earliest stereo pairname date, to be mapped to STAC `start_datetime` and `datetime` properties
- `acqdate_max`: latest stereo pairname date, to be mapped to STAC `end_datetime` property
I tested creating JSONs for some of the REMA mosaic tiles, and it appears the new attributes are being created correctly.
Here's how the new attributes appear in the JSONs:
```
"pairname_ids": ["WV01_20121222_1020010020797E00_102001001E757700", "WV01_20150224_102001003756F300_102001003B7C9F00", "WV01_20150308_102001003853C900_1020010039025E00", "WV01_20150314_102001003E4FC900_102001003B90AD00", …
```
=> Add `SetsmTile` attributes for mosaic tile STAC work

lib/dem.py
Replaces old broken code for setting release version attribute from strip JSONs
=> Set `SetsmDem.release_version` attribute from s2s version if necessary

lib/dem.py
Previously xtrack pairnames were not properly parsed from the tile meta.txt files and never made it into the `SetsmTile.component_list` attribute.
@klassenjs requested that the `SetsmTile.release_version` attribute always starts with a 'v' prefix (like 'v2.0') as it is when the attribute is set through parsing of the mosaic tile filename.
=> Mosaic tile index fixes

apply_setsm_registration.py, divide_setsm_tiles.py, generate_browse_setsm.py, reproject_setsm.py, resample_setsm.py, resample_setsm_tiles.py
Addresses issue https://github.com/PolarGeospatialCenter/pgcdemtools/issues/59.
- Round DEM and MAD values to 1/128 meters to greatly increase compression efficiency.
- Add `-ovr NONE` to gdalwarp and gdal_translate calls. Only when downsampling is this necessary to avoid error propagation when overviews are used for resampling. But add it to all calls just to get used to it.
- Add LZW predictor setting to GTiff output settings.
- Add debug mode to `resample_setsm_tiles.py` script.
=> (WIP) Round DEM and MAD raster values to 1/128 meters, and add new standard `-ovr NONE` arg to GDAL calls

index_setsm.py, lib/utils.py
Looks for either `FileGDB` or `OpenFileGDB` drivers when writing out gdb indexes.
=> Add OpenFileGDB capability

resample_setsm_tiles.py
Added the `nargs='+'` option to the `--components` argument, making the `args.components` a list of the components to be run. It's always a list, even if only one component is provided or the default 'all' is used.
I needed this to resample both the dem and browse rasters for ArcticDEM tiles we're doing the QC filter work on.
Example usage:
```
python ~/scratch/repos/pgcdemtools/resample_setsm_tiles.py ./ -c all -tr 100 -sr 10 --output-cogs --depth 2 --pbs -c dem browse
```
=> Extend option to specify multiple components for DEM tile resample

index_setsm.py
@clairecporter I think we maybe ought to have the multiple `if ogr_driver_str ==` / `if ogr_driver_str in` test cases here turned into an `if ... elif ... else [unsupported driver, ERROR]` construct, to be safe.
=> Test if dst GDB already exists, OpenFileGDB driver

index_setsm.py, lib/dem.py, lib/utils.py
-- IMPORTANT NOTE --
The most important change in this PR is in how index_setsm.py handles the "duplicate key value violates unique constraint" error when add records to the target table. Previously, the entire index_setsm.py process would error out upon hitting the first record that trips the unique constraint error. Now it will just print error messages and skip over those records.
See individual commits for details on the particular tweaks.
This needs more testing, but I think these changes touch on some really important areas for improvement in the error handling.
I believe NASA has been running with these changes applied as a patch to their pgcdemtools code.
=> Skip over unique constraint duplicate record errors, adjust error logging in index_setsm.py

lib/dem.py
Upon creating a `SetsmScene` record, check source scene component files:
- One of the possible three DEM rasters exists and is not zero-length
- All three required {ortho, matchtag, meta} files exist and are not zero-length
- If either the `ortho2.tif` or `info50cm.txt` file exist, it is not zero-length
=> More complete check of `SetsmScene` source file existence

index_setsm.py, lib/dem.py, tests/func_test_index.py
This PR fixes a bug where the alignment statistics for the component scene DEMs were not being gathered when a DEM object was built from mdf file instead of the original txt file.  This resulted in missing index attributes. This PR also adds a test for field and value parity between indexes built with either method.
=> Rebuild strip DEMs scene metadata from .mdf files

resample_setsm.py
Allow the resampling of `_bitmask.tif` images to different resolutions using the nearest neighbor method.
=> add bitmask as component option to resample_setsm.py

package_setsm.py, slurm_package.sh
Problem: package_setsm.py would never call a strip complete if rasterproxies were not built.
Solution: checked for the correct argument.
=> package strip rasterproxy completeness bug

shelve_setsm_strips_simple.py
Allow shelve_setsm_strips_simple.py to shelve DEMs with an mdf.txt instead of a meta.txt file.  Also clarify the argparse description
=> Update shelve_setsm_strips to use mdf.txt

README.md, lib/utils.py, tests/test_index.py, tests/test_package.py
Problem: After conversion to pytest, some tests failed on windows.
Solution: Repaired tests where possible and added skip markers if the tested functionality is not used on windows.
=> Adapt for windows

package_setsm.py
`--project` is only needed for building raster proxy files, so this PR makes it contingent on the `--build-rasterproxy` option instead of globally required. This is needed for FRIDGE to work with DEM strips.
=> Make project argument optional in package_setsm.py
