index_setsm.py
lib/dem.py
tests/func_test_index.py

1) Postgres-specific field attribute mapping bug fixes.
2) Add check for old style schema on append.

Indexer bug fixes

---

lib/dem.py

These changes to `index_setsm.py` go in step with the changes in `setsm-utils` PR: https://github.umn.edu/pgc/setsm-utils/pull/12

Handle filenames of subtiled scene DEM result files

---

apply_setsm_registration.py
calc_density.py
calc_density_tiles.py
copy_dems.py
divide_setsm_tiles.py
index_setsm.py
lib/dem.py
lib/taskhandler.py
lib/utils.py
package_setsm.py
package_setsm_tiles.py
reproject_setsm.py
shelve_setsm_by_date.py
shelve_setsm_by_geocell.py
shelve_setsm_by_shp.py
tests/func_test_index.py
tests/unit_test_taskhandler.py
tests/unit_test_utils.py

Includes an important bugfix for the issue brought up by a kind user: https://github.com/PolarGeospatialCenter/pgcdemtools/issues/12

Update osgeo import syntax, bugfix

---

index_setsm.py
lib/dem.py
lib/taskhandler.py
package_setsm.py
tests/func_test_index.py

Also fixed:
-  a bug in the taskhandler around single-character options
- DSP DEM handling with custom paths and `--check` functionality in the indexer

Update packaging to handle v4 strips and tiles

---

index_setsm.py
lib/dem.py

@clairecporter I also mentioned the UTM 60 N/S EPSG issue in the #dem-production channel. Let's talk about fixing this error in the existing DEM tables on Sandwich when you're back. It should be pretty easy to fix (I think) but I want to make sure we follow the right procedure in doing so.

BW custom path prefix, UTM 60 N/S EPSG index field value fix

---

lib/dem.py

JSON files for scene and strip DEMs built before the utm zone 60 n/s epsg code bug was fixed have epsg = "".  This PR chacks the epsg value when building DEM object from json and repairs the epsg code if it's invalid.

Add check/recalculation for valid epsg code in DEMs built from JSON

---

index_setsm.py
lib/dem.py
tests/func_test_index.py

We'll have to figure out how NASA will want to handle the strip update from v4 to v4.1 from an organizational standpoint, considering there could be a new strip version in the future as well.
The same goes for the Black Pearl bucket structure, when we eventually start writing strips to tape.

Build strip DEM custom path using 's2s_version' attribute

---

index_setsm.py
lib/dem.py
lib/utils.py
package_setsm.py
tests/func_test_index.py

- Added predictor and overview resampling to COG creation in package_setsm.py
- Added cloud, water, and valid area metrics to dem.py SetsmDem object and incorporated them into indexes and mdfs
- Added average values for convergence angle, expected height accuracy, and sun elev to dem.py SetsmDem object and incorporated them into indexes and mdfs
- Updated tests
- Minor changes in MDF layout

Package and index updates

---

index_setsm.py
lib/dem.py
lib/utils.py
package_setsm.py

Package_setsm.py updates:
- Changed package filter DEMs threshold to use the new valid area attribute
- Added EPSG code formatting to COG rasters
- Other bug fixes around the new attributes

Change package threshold

---

package_setsm.py

Added option to create a raster proxy MRF file.  Fixed a bug in the COG conversion.

Package rasterproxy

---

index_setsm.py
lib/dem.py
lib/utils.py
package_setsm.py
package_setsm_tiles.py

This PR updates the packaging tools to include building raster proxies.  It also has a few minor additions to dem.py and utils.py that should affect index_setsm.py and no other parts of the repo (I pulled out the getWrappedGeometry function and put it in the utils library since it is now used in three places).

Raster proxy functionality for packaging

---

lib/taskhandler.py
resample_setsm_tiles.py

This PR is primarily focused on the reample_setsm_tiles.py tool.
- Merge quad tiles into a supertile
- Consolidate metadata during merge
- Output COGs

Update code around downsampling 2m mosaic tiles

---

index_setsm.py
lib/dem.py
lib/utils.py
tests/func_test_index.py

This PR includes a couple additional changes on top of PR https://github.com/PolarGeospatialCenter/pgcdemtools/pull/68

New field data type bugfixes

---

index_setsm.py
lib/utils.py

As always, I haven't had enough time to test! But changes should have minimal impact on original workings of the indexer.

New toggle for writing "tile release" format index fields

---

package_setsm.py
package_setsm_tiles.py

- Needs more testing 
- Currently only applied improvements to mosaic file packaging
- Should apply improvements to strip file packaging as well

Improve handling of errors in SETSM product packaging scripts

---

index_setsm.py

Important commits:
- [Remove password from PG connection string for logger print](https://github.com/PolarGeospatialCenter/pgcdemtools/commit/d24c9dff9661c54817b38ed224b2ecf74c3219d3)
- [Deprecate PG config 'danco' connection name](https://github.com/PolarGeospatialCenter/pgcdemtools/commit/c9520cdfbb209d8407abf5b27d142b7b7874af80)

Fix security issue in logging, change expected Danco service name in PG config

---

index_setsm.py
lib/dem.py

Reverts PolarGeospatialCenter/pgcdemtools#84

Revert "Index setsm bugfix"

---

sql/create_view_scene_dem_master.sql
sql/create_view_strip_dem_master.sql

Sql update

---

package_setsm.py
package_setsm_tiles.py
tests/test_package.py

Add slurm job name option to packager scripts for easier tracking of compute resources in FRIDGE.

Add slurm job name option to packagers

---

sql/create_view_scene_dem_all.sql

With all the data pulled back from CSDA, the `dem.scene_dem_all` materialized view should no linger represent those records even if they are not superseded by local versions.

Remove 50cm DEMs at CSDA from dem.scene_dem_all view definition
